title = "GitLeaks Configuration"

[allowlist]
paths = [
    '''node_modules''',
    '''dist''',
    '''package-lock.json''',
    '''yarn.lock''',
    '''__snapshots__''',
]

[[rules]]
id = "aws-access-key-id"
description = "AWS Access Key ID"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''

[[rules]]
id = "aws-secret-access-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''

[[rules]]
id = "password-in-url"
description = "Password in URL"
regex = '''[a-zA-Z]{3,10}://[^/\s:@]*?:[^/\s@]*?@[^/\s]*'''

[[rules]]
id = "generic-credentials"
description = "Generic Credentials"
regex = '''(?i)(dbpassword|dbuser|dbname|dbhost|api_key|apikey|secret|password|guid|credentials)(.{0,20})?['\"][0-9a-zA-Z-_!{}/=]{4,120}['\"]'''

[[rules]]
id = "jwt"
description = "JSON Web Token"
regex = '''(?i)eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$'''

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (?:RSA|OPENSSH|DSA|EC|PGP) PRIVATE KEY( BLOCK)?-----''' 