title = "GitLeaks Configuration"

[allowlist]
paths = [
    '''node_modules''',
    '''dist''',
    '''package-lock.json''',
    '''yarn.lock''',
    '''__snapshots__''',
    '''README.md''',
    '''\.md$'''
]

description = "allowlisted files and patterns"
regexes = [
    '''localhost''',
    '''127\.0\.0\.1'''
]

# General rules

[[rules]]
id = "aws-credentials"
description = "AWS Credentials"
regex = '''(?i)(aws_access_key|aws_secret_key)\s*=\s*["'][^"']{8,}["']'''

# Removed allowlist for AWS credentials to catch example keys

[[rules]]
id = "postgres-url"
description = "Postgres Connection URL"
regex = '''(?i)(postgres(?:ql)?:\/\/[^:\s]+:[^@\s]+@[^\s]+)'''

# Removed example.com from allowlist to catch example.com database URLs

[[rules]]
id = "mongodb-url"
description = "MongoDB Connection URL"
regex = '''(?i)(mongodb:\/\/[^:\s]+:[^@\s]+@[^\s]+)'''

[rules.allowlist]
regexes = ['''localhost''', '''127\.0\.0\.1''']

[[rules]]
id = "github-token"
description = "GitHub Token"
regex = '''(?i)ghp_[0-9a-zA-Z]{36}'''

[rules.allowlist]
regexes = ['''ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx''']

[[rules]]
id = "google-api"
description = "Google API Key"
regex = '''(?i)AIza[0-9A-Za-z\\-_]{35}'''

[rules.allowlist]
regexes = ['''AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx''']

[[rules]]
id = "jwt"
description = "JWT Token"
regex = '''(?i)eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'''

[rules.allowlist]
regexes = ['''eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.eyJzdWIiOiIxMjM0NTY3ODkwIn0\.''']

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''(?s)-----BEGIN.*?PRIVATE KEY-----.*?-----END.*?PRIVATE KEY-----'''

[rules.allowlist]
regexes = ['''-----BEGIN RSA PRIVATE KEY-----\s+MIIEogIBAAKCAQEA7bq98D12ptBNZwvNUs\+kfmL2kCvP0RH\+RyHF0I[0-9]=\s+-----END RS''']

# Additional rules to catch specific example credentials

[[rules]]
id = "aws-example-key"
description = "AWS Example Access Key"
regex = '''AKIAIOSFODNN7EXAMPLE'''

[[rules]]
id = "aws-example-secret"
description = "AWS Example Secret Key"
regex = '''wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'''