title = "GitLeaks Configuration"

[allowlist]
paths = [
    '''node_modules''',
    '''dist''',
    '''package-lock.json''',
    '''yarn.lock''',
    '''__snapshots__''',
]

[[rules]]
id = "aws-credentials"
description = "AWS Credentials"
regex = '''(?i)(aws_access_key|aws_secret_key)\s*=\s*["'][^"']+["']'''

[[rules]]
id = "postgres-url"
description = "Postgres Connection URL"
regex = '''(?i)(postgres(?:ql)?:\/\/[^:\s]+:[^@\s]+@[^\s]+)'''

[[rules]]
id = "mongodb-url"
description = "MongoDB Connection URL"
regex = '''(?i)(mongodb:\/\/[^:\s]+:[^@\s]+@[^\s]+)'''

[[rules]]
id = "github-token"
description = "GitHub Token"
regex = '''(?i)ghp_[0-9a-zA-Z]{36}'''

[[rules]]
id = "google-api"
description = "Google API Key"
regex = '''(?i)AIza[0-9A-Za-z\\-_]{35}'''

[[rules]]
id = "jwt"
description = "JWT Token"
regex = '''(?i)eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'''

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''(?s)-----BEGIN.*?PRIVATE KEY-----.*?-----END.*?PRIVATE KEY-----''' 