# .gitleaks.toml
title = "Enhanced Gitleaks Config"

[allowlist]
description = "Global allowlist rules"
paths = [
    '''node_modules''',
    '''vendor''',
    '''yarn.lock''',
    '''package-lock.json''',
    '''__snapshots__''',
    '''.gitleaks.toml'''
]

# Files that contain the word "test" or are in test directories
regexes = [
    '''(?i)test''',
    '''(?i)fixture''',
]

# Generic API Key
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey|secret)[_-]?([0-9a-zA-Z]{32,45})'''
secretGroup = 2
keywords = ["api", "apikey", "secret", "key"]
entropy = 3.5

# AWS
[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["aws", "credentials"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws[_-]?secret[_-]?access[_-]?key[_-]?[ '\"]?[=:][ '\"]?([0-9a-zA-Z/+]{40})'''
secretGroup = 1
tags = ["aws", "credentials"]

# Database Connection Strings
[[rules]]
id = "database-connection-string"
description = "Database Connection String"
regex = '''(?i)(mongodb|postgresql|mysql|redis):\/\/[^\/\s]+'''
tags = ["database", "connection-string"]

# Google
[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
tags = ["google", "api"]

# GitHub
[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''gh[ps]_[0-9a-zA-Z]{36}'''
tags = ["github", "pat"]

# JWT Tokens
[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''ey[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$'''
tags = ["jwt", "token"]

# Private Keys
[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN ((RSA|DSA|EC|PGP|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
tags = ["key", "private"]