title = "GitLeaks Configuration"

[allowlist]
paths = [
    '''node_modules''',
    '''dist''',
    '''package-lock.json''',
    '''yarn.lock''',
    '''__snapshots__''',
]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey|secret)[_-]?(key)?["\s]*[=:]["\s]*[A-Za-z0-9+/=]{16,}'''
secretGroup = 0
keywords = ["key", "api", "token", "secret"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''(AKIA[0-9A-Z]{16})'''
secretGroup = 1

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)(aws_secret|aws_secret_key|aws_secret_access_key)["\s]*[=:]["\s]*([A-Za-z0-9/+=]{40})'''
secretGroup = 2

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'''

[[rules]]
id = "database-connection-string"
description = "Database Connection String"
regex = '''(?i)(mongodb|postgresql|postgres)(?:.*?)\:\/\/[^\/\s]+'''

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''(?i)-----BEGIN.*?PRIVATE KEY-----[\s\S]*?-----END.*?PRIVATE KEY-----'''

[[rules]]
id = "password-in-url"
description = "Password in URL"
regex = '''[a-zA-Z]{3,10}:\/\/[^\/\s:@]*?:[^\/\s@]*?@[^\/\s]*'''

[[rules]]
id = "generic-secret"
description = "Generic Secret"
regex = '''(?i)['"]?(?:password|secret|token|key)['"]?\s*[:=]\s*['"][^'"]{8,}['"]''' 